stages:
  - sync

sync_from_github:
  stage: sync
  only:
    - web  # 仅允许手动触发
  script:
    - echo "开始从 GitHub 同步代码..."
    - git config --global user.name "GitLab Sync Bot"
    - git config --global user.email "gitlab-bot@example.com"
    - git remote add github https://github.com/zitzhen/CoCo-Community.git || true  # 添加 GitHub 远程（会忽略错误）
    - git fetch github  # 获取 GitHub 最新代码
    - git checkout main  # 切换到 GitLab 的主分支（如 main 或 master）
    - git reset --hard github/main  # 强制用 GitHub main 分支覆盖本地
    - git push origin main --force  # 强制推送到 GitLab
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"  # 仅允许手动触发