name: Update control folder list

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - 'control/**'

jobs:
  generate-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}  # 检出合并后的代码

      - name: Generate list.json
        id: generate
        run: |
          cd control || exit 1
          dirs=$(find . -mindepth 1 -maxdepth 1 -type d ! -name "js" ! -name "css" -printf '%P\n' | jq -R -s -c 'split("\n")[:-1]')
          cd ..
          new_json="{\"list\": $dirs}"
          echo "$new_json" > list.json

          # 检查与 main 分支的差异
          git show origin/main:list.json > old_list.json 2>/dev/null || echo "{}" > old_list.json
          if diff -q old_list.json list.json; then
            echo "No changes detected in list.json"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in list.json"
            git add list.json
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request (if changes detected)
        if: steps.generate.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update list.json with latest control folders"
          title: "Update control folder list"
          body: "Automatically updated list of folders in control directory (excluding js and css)"
          branch: "update-control-list-$(date +%Y%m%d%H%M%S)"  # 改用合法的时间格式
          base: main  # 目标分支
          delete-branch: true
          labels: "automated"