name: Generate Sitemap
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # 每天运行一次

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Find control subdirectories
        id: find-control
        run: |
          # 获取control目录下所有一级子目录（排除css和js）
          dirs=$(find control -maxdepth 1 -mindepth 1 -type d -not -name "css" -not -name "js" -printf "%p/,")
          # 格式化输出为逗号分隔的字符串
          echo "additional_paths=${dirs%,}" >> $GITHUB_OUTPUT

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://cc.zitzhen.cn"
          exclude-paths: "404.html,google46eebdeb664df7df.html,control/css,control/js"
          additional-paths: ${{ steps.find-control.outputs.additional_paths }}
          slash: true
          preserve-trailing-slash: false

      - name: Check sitemap.xml exists
        run: ls -l sitemap.xml

      - name: Set git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update sitemap"
          title: "Update sitemap"
          body: "自动生成并更新 sitemap.xml"
          branch: "auto/update-sitemap-${{ github.run_id }}"
          base: main
          add-paths: sitemap.xml
          delete-branch: true