name: Generate Sitemap
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # 每天运行一次

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://cc.zitzhen.cn"
          #change-frequency: "weekly" 忽视已被移除的参数
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap"
          git push
